
<html>

<head>

</head>
<body>
<h1>publicaciones</h1>

<?php

if(!empty($_SESSION['user']) && $_SESSION['user']->getRol()>1) 
    echo "<a href='index.php?newPub=1'>Subir publicacion</a>";

echo "<br>";
foreach($pubs as $pub){
    echo '<img src="public/img/'.$pub->getImage().'" width="100px"/>';
    echo $pub->getTitle().$pub->getText()."<br>";

    //formulario comment
    echo '<form action="index.php" method="POST">
    <input type="text" name="comment" placeholder="escribe tu comentario">
    <input type="submit" name="newComment" value="Publicar"/>
</form>';
}

?>




<form action="index.php" method="POST">
    <input type="text" name="username">
    <input type="password" name="password">
    <input type="submit" name="login" value="entrar">
</form>
</body>
</html>